/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.controller;

import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.spldeolin.beginningmind.api.exception.ServiceException;
import com.spldeolin.beginningmind.input.BuyerInput;
import com.spldeolin.beginningmind.service.BuyerService;

/**
 * “买家”管理
 *
 * @author Deolin 2018/5/26
 */
@RestController
@RequestMapping("/buyer")
@Validated
public class BuyerController {

    @Autowired
    private BuyerService buyerService;

    /**
     * 创建一个“买家”
     */
    @PostMapping("/create")
    Object create(@RequestBody @Valid BuyerInput buyerInput) {
        return buyerService.createEX(buyerInput.toModel());
    }

    /**
     * 获取一个“买家”
     */
    @GetMapping("/get/{id}")
    Object get(@PathVariable Long id) {
        return buyerService.get(id).orElseThrow(() -> new ServiceException("买家不存在或是已被删除"));
    }

    /**
     * 更新一个“买家”
     */
    @PostMapping("/update/{id}")
    void update(@PathVariable Long id, @RequestBody @Valid BuyerInput buyerInput) {
        buyerService.updateEX(buyerInput.toModel().setId(id));
    }

    /**
     * 删除一个“买家”
     */
    @PostMapping("/delete/{id}")
    void delete(@PathVariable Long id) {
        buyerService.deleteEX(id);
    }

    /**
     * 获取一批“买家”
     */
    @GetMapping("/search")
    Object page(@RequestParam(defaultValue = "1") Integer pageNo,
            @RequestParam(defaultValue = "10") @Max(1000) Integer pageSize) {
        return buyerService.page(pageNo, pageSize);
    }

    /**
     * 删除一批“买家”
     */
    @PostMapping("/batchDelete")
    Object delete(@RequestBody List<Long> ids) {
        return buyerService.deleteEX(ids);
    }

}