/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.controller;

import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.spldeolin.beginningmind.api.exception.ServiceException;
import com.spldeolin.beginningmind.input.GoodsInput;
import com.spldeolin.beginningmind.service.GoodsService;

/**
 * “商品”管理
 *
 * @author Deolin 2018/5/26
 */
@RestController
@RequestMapping("/goods")
@Validated
public class GoodsController {

    @Autowired
    private GoodsService goodsService;

    /**
     * 创建一个“商品”
     */
    @PostMapping("/create")
    Object create(@RequestBody @Valid GoodsInput goodsInput) {
        return goodsService.createEX(goodsInput.toModel());
    }

    /**
     * 获取一个“商品”
     */
    @GetMapping("/get/{id}")
    Object get(@PathVariable Long id) {
        return goodsService.get(id).orElseThrow(() -> new ServiceException("商品不存在或是已被删除"));
    }

    /**
     * 更新一个“商品”
     */
    @PostMapping("/update/{id}")
    void update(@PathVariable Long id, @RequestBody @Valid GoodsInput goodsInput) {
        goodsService.updateEX(goodsInput.toModel().setId(id));
    }

    /**
     * 删除一个“商品”
     */
    @PostMapping("/delete/{id}")
    void delete(@PathVariable Long id) {
        goodsService.deleteEX(id);
    }

    /**
     * 获取一批“商品”
     */
    @GetMapping("/search")
    Object page(@RequestParam(defaultValue = "1") Integer pageNo,
            @RequestParam(defaultValue = "10") @Max(1000) Integer pageSize) {
        return goodsService.page(pageNo, pageSize);
    }

    /**
     * 删除一批“商品”
     */
    @PostMapping("/batchDelete")
    Object delete(@RequestBody List<Long> ids) {
        return goodsService.deleteEX(ids);
    }

}