/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.controller;

import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.spldeolin.beginningmind.api.exception.ServiceException;
import com.spldeolin.beginningmind.controller.annotation.PermissionDisplayName;
import com.spldeolin.beginningmind.input.SellerInput;
import com.spldeolin.beginningmind.service.SellerService;

/**
 * “卖家”管理
 *
 * @author Deolin 2018/5/26
 */
@RestController
@RequestMapping("/seller")
@Validated
public class SellerController {

    @Autowired
    private SellerService sellerService;

    /**
     * 创建一个“卖家”
     */
    @PermissionDisplayName("创建卖家")
    @PostMapping("/create")
    Object create(@RequestBody @Valid SellerInput sellerInput) {
        return sellerService.createEX(sellerInput.toModel());
    }

    /**
     * 获取一个“卖家”
     */
    @PermissionDisplayName("卖家详情")
    @GetMapping("/get/{id}")
    Object get(@PathVariable Long id) {
        return sellerService.get(id).orElseThrow(() -> new ServiceException("卖家不存在或是已被删除"));
    }

    /**
     * 更新一个“卖家”
     */
    @PermissionDisplayName("更新卖家")
    @PostMapping("/update/{id}")
    Object update(@PathVariable Long id, @RequestBody @Valid SellerInput sellerInput) {
        sellerService.updateEX(sellerInput.toModel().setId(id));
        return null;
    }

    /**
     * 删除一个“卖家”
     */
    @PermissionDisplayName("删除卖家")
    @PostMapping("/delete/{id}")
    Object delete(@PathVariable Long id) {
        sellerService.deleteEX(id);
        return null;
    }

    /**
     * 获取一批“卖家”
     */
    @PermissionDisplayName("卖家列表")
    @GetMapping("/search")
    Object page(@RequestParam(defaultValue = "1") Integer pageNo,
            @RequestParam(defaultValue = "10") @Max(1000) Integer pageSize) {
        return sellerService.page(pageNo, pageSize);
    }

    /**
     * 删除一批“卖家”
     */
    @PermissionDisplayName("批量删除卖家")
    @PostMapping("/batchDelete")
    Object delete(@RequestBody List<Long> ids) {
        return sellerService.deleteEX(ids);
    }

}