/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.api.CommonMapper;
import com.spldeolin.beginningmind.model.SecurityRoles2permissions;

/**
 * “角色与权限的关联”数据库映射
 *
 * @author Deolin 2018/5/15
 */
@Mapper
public interface SecurityRoles2permissionsMapper extends CommonMapper<SecurityRoles2permissions> {
}