########################
##                    ##
##     Production     ##
##                    ##
########################

debug: false

server:

  port: # TODO 生产端口

  context-path: /

spring:

  datasource:
    source1:
      url: # TODO 生产数据库
      username: #TODO 生产数据库
      password: #TODO 生产数据库

  redis:
    host: #TODO 生产Redis
    port: #TODO 生产Redis
    password: #TODO 生产Redis

  data:
    mongodb:
      uri: #TODO 生产MongoDB

  activemq:
    broker-url: #TODO 生产activeMQ
    spring.activemq.user: #TODO 生产activeMQ
    spring.activemq.password: #TODO 生产activeMQ

logging:

  config: classpath:log4j2/log4j2-prod.yml

core:

  address: # TODO 生产域名与端口

  file:
    mapping: /static/
    location: # TODO 生产环境静态文件目录

  wechat:
    a: a

  qiniu:
    a: a

  yunpian:
    a: a
