/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import com.spldeolin.beginningmind.model.SecurityUsers2roles;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “用户与权限的关联”Input类
 *
 * @author Deolin 2018/5/28
 */
@Data
@Accessors(chain = true)
public class SecurityUsers2rolesInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    private Long userId;

    private Long roleId;

    private static final long serialVersionUID = 1L;

    public SecurityUsers2roles toModel() {
        return SecurityUsers2roles.builder().id(id).updatedAt(updatedAt).userId(userId).roleId(roleId).build();
    }

}