/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.validation.constraints.Size;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.spldeolin.beginningmind.model.SecurityPermission;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “权限”Input类
 *
 * @author Deolin 2018/5/16
 */
@Data
@Accessors(chain = true)
public class SecurityPermissionInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    @JsonProperty("updated_at")
    private LocalDateTime updatedAt;

    /**
     * 权限名
     */
    @Size(max = 255)
    private String name;

    /**
     * 请求方法@RequiresPermissions注解属性的映射
     */
    @JsonProperty("requires_permissions_mapping")
    @Size(max = 255)
    private String requiresPermissionsMapping;

    private static final long serialVersionUID = 1L;

    public SecurityPermission toModel() {
        return SecurityPermission.builder().id(id).updatedAt(updatedAt).name(name).requiresPermissionsMapping(
                requiresPermissionsMapping).build();
    }

}