/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.service;

import javax.servlet.http.HttpServletRequest;
import org.aspectj.lang.JoinPoint;
import com.spldeolin.beginningmind.core.api.CommonService;
import com.spldeolin.beginningmind.core.aspect.dto.RequestResult;
import com.spldeolin.beginningmind.core.model.RequestTrack;

/**
 * “请求轨迹”业务
 *
 * @author Deolin 2018/8/4
 */
public interface RequestTrackService extends CommonService<RequestTrack> {

    /**
     * 设置 切点、Request、登录者ID，生成请求轨迹
     */
    RequestTrack setJoinPointAndHttpRequest(JoinPoint joinPoint, HttpServletRequest request, Long userId);

    /**
     * 补全请求轨迹信息，并保存请求轨迹
     */
    void completeAndSaveTrack(RequestTrack track, HttpServletRequest request, Object dataObject);

    /**
     * 补全请求轨迹信息，并保存请求轨迹
     */
    void completeAndSaveTrack(RequestTrack track, HttpServletRequest request, RequestResult requestResult);


}