/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.service;

import java.util.List;
import com.spldeolin.beginningmind.core.api.CommonService;
import com.spldeolin.beginningmind.core.api.dto.Page;
import com.spldeolin.beginningmind.core.api.dto.PageParam;
import com.spldeolin.beginningmind.core.model.SecurityRoles2menus;

/**
 * “角色与菜单的关联”业务
 *
 * @author Deolin 2018/7/10
 */
public interface SecurityRoles2menusService extends CommonService<SecurityRoles2menus> {

    /**
     * 创建一个“角色与菜单的关联”
     * （附带业务校验）
     *
     * @param securityRoles2menus 待创建“角色与菜单的关联”
     * @return 自增ID
     */
    Long createEX(SecurityRoles2menus securityRoles2menus);

    /**
     * 获取一个“角色与菜单的关联”
     * （附带业务校验）
     *
     * @param id 待获取“角色与菜单的关联”的ID
     * @return “角色与菜单的关联”
     */
    SecurityRoles2menus getEX(Long id);

    /**
     * 更新一个“角色与菜单的关联”
     * （附带业务校验）
     *
     * @param securityRoles2menus 待更新“角色与菜单的关联”
     */
    void updateEX(SecurityRoles2menus securityRoles2menus);

    /**
     * 删除一个“角色与菜单的关联”
     * （附带业务校验）
     *
     * @param id 待删除“角色与菜单的关联”的ID
     */
    void deleteEX(Long id);

    /**
     * 删除多个资源
     * （附带业务校验，并返回详细情况）
     *
     * @param ids 待删除资源的ID列表
     * @return 删除情况
     */
    String deleteEX(List<Long> ids);

    /**
     * 分页获取资源
     *
     * @param pageParam 页码和每页条目数
     * @return Page 分页对象
     */
    Page<SecurityRoles2menus> page(PageParam pageParam); // 根据具体需求拓展这个方法（追加搜索用参数等）

}