/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.service;

import java.util.Map;
import com.spldeolin.beginningmind.core.api.CommonService;
import com.spldeolin.beginningmind.core.model.User2organization;

/**
 * “用户与组织架构的关联”业务
 *
 * @author Deolin 2018/8/28
 */
public interface User2organizationService extends CommonService<User2organization> {

    Map<Long, Integer> mapUserCounts();

}