/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotBlank;
import com.spldeolin.beginningmind.core.api.ControllerAspectPreprocess;
import com.spldeolin.beginningmind.core.model.Organization;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “组织架构”Input类
 *
 * @author Deolin 2018/8/28
 */
@Data
@Accessors(chain = true)
public class OrganizationInput implements Serializable, ControllerAspectPreprocess {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 父组织架构ID（0代表这是个顶层组织）
     */
    private Long parentId;

    /**
     * 名称
     */
    @NotBlank
    @Size(max = 255)
    private String name;

    private static final long serialVersionUID = 1L;

    public Organization toModel() {
        return Organization.builder().id(id).updatedAt(updatedAt).parentId(parentId).name(name).build();
    }

    @Override
    public void nullToEmptyAndTrim() {
        if (name != null) {
            name = name.trim();
        } else {
            name = "";
        }
    }

}
// id, updatedAt, parentId, name