/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import com.spldeolin.beginningmind.core.model.SecurityUsers2menus;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “用户与菜单的关联”Input类
 *
 * @author Deolin 2018/7/10
 */
@Data
@Accessors(chain = true)
public class SecurityUsers2menusInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    private Long userId;

    private Long menuId;

    private static final long serialVersionUID = 1L;

    public SecurityUsers2menus toModel() {
        return SecurityUsers2menus.builder().id(id).updatedAt(updatedAt).userId(userId).menuId(menuId).build();
    }

}