/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import com.spldeolin.beginningmind.core.model.SecurityRoles2menus;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “角色与菜单的关联”Input类
 *
 * @author Deolin 2018/7/10
 */
@Data
@Accessors(chain = true)
public class SecurityRoles2menusInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 审计字段 删除标记（-1代表未被删除，其他代表被删除）
     */
    private Long deletionFlag;

    private Long roleId;

    private Long menuId;

    private static final long serialVersionUID = 1L;

    public SecurityRoles2menus toModel() {
        return SecurityRoles2menus.builder().id(id).updatedAt(updatedAt).deletionFlag(deletionFlag).roleId(
                roleId).menuId(menuId).build();
    }

}