/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.*;
import org.hibernate.validator.constraints.*;
import lombok.Data;
import lombok.experimental.Accessors;
import com.spldeolin.beginningmind.core.model.SecurityMenu;

/**
 * “菜单”Input类
 *
 * @author Deolin 2018/7/10
 */
@Data
@Accessors(chain = true)
public class SecurityMenuInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 审计字段 删除标记（-1代表未被删除，其他代表被删除）
     */
    private Long deletionFlag;

    /**
     * 显示名
     */
    @Length(max = 255)
    private String display;

    /**
     * 右侧内容网页的URL
     */
    @Length(max = 255)
    private String url;

    /**
     * 父菜单显示名
     */
    @Length(max = 255)
    private String parentDisplay;

    private static final long serialVersionUID = 1L;

    public SecurityMenu toModel() {
        return SecurityMenu.builder().id(id).updatedAt(updatedAt).deletionFlag(deletionFlag).display(display).url(
                url).parentDisplay(parentDisplay).build();
    }

}