/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;
import com.spldeolin.beginningmind.core.api.valid.annotation.Mobile;
import com.spldeolin.beginningmind.core.api.valid.annotation.Option;
import com.spldeolin.beginningmind.core.model.SecurityUser;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “用户”Input类
 *
 * @author Deolin 2018/5/29
 */
@Data
@Accessors(chain = true)
public class SecurityUserInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * “用户名”
     */
    @NotBlank
    @Length(max = 16)
    private String username;

    /**
     * 手机号
     */
    @Mobile
    @Length(max = 20)
    private String mobile;

    /**
     * E-Mail
     */
    @Email
    @Length(max = 255)
    private String email;

    /**
     * 能否登录
     */
    @NotNull
    private Boolean enableSign;

    /**
     * 昵称
     */
    @Length(max = 255)
    private String nickname;

    /**
     * 头像URL
     */
    @Length(max = 255)
    private String headerUrl;

    /**
     * 性别
     */
    @Length(max = 6)
    @Option({"", "male", "female"})
    private String sex;

    /**
     * 联系地址（省）
     */
    @Length(max = 6)
    private String province;

    /**
     * 联系地址（市）
     */
    @Length(max = 6)
    private String city;

    /**
     * 联系地址（区）
     */
    @Length(max = 6)
    private String area;

    private static final long serialVersionUID = 1L;

    public SecurityUser toModel() {
        return SecurityUser.builder().id(id).updatedAt(updatedAt).username(username).mobile(mobile).email(
                email).enableSign(enableSign).nickname(nickname).headerUrl(headerUrl).sex(sex).province(province).city(
                city).area(area).build();
    }

}