/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import com.spldeolin.beginningmind.core.model.SecurityRoles2permissions;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “角色与权限的关联”Input类
 *
 * @author Deolin 2018/5/26
 */
@Data
@Accessors(chain = true)
public class SecurityRoles2permissionsInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    private Long roleId;

    private Long permissionId;

    private static final long serialVersionUID = 1L;

    public SecurityRoles2permissions toModel() {
        return SecurityRoles2permissions.builder().id(id).updatedAt(updatedAt).roleId(roleId).permissionId(
                permissionId).build();
    }

}