/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.input;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;
import com.spldeolin.beginningmind.core.api.valid.annotation.Mobile;
import com.spldeolin.beginningmind.core.model.User;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * “用户”Input类
 *
 * @author Deolin 2018/8/4
 */
@Data
@Accessors(chain = true)
public class UserInput implements Serializable {

    /**
     * ID
     */
    private Long id;

    /**
     * 审计字段 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 名字
     */
    @Size(max = 255)
    private String name;

    /**
     * 手机号
     */
    @Size(max = 20)
    @Mobile
    private String mobile;

    /**
     * E-mail
     */
    @Size(max = 255)
    @Email
    private String email;

    private static final long serialVersionUID = 1L;

    public User toModel() {
        return User.builder().id(id).updatedAt(updatedAt).name(name).mobile(mobile).email(email).build();
    }

}
// id, updatedAt, name, mobile, email