/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.service.impl;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.github.pagehelper.PageHelper;
import com.spldeolin.beginningmind.api.CommonServiceImpl;
import com.spldeolin.beginningmind.api.dto.Page;
import com.spldeolin.beginningmind.api.exception.ServiceException;
import com.spldeolin.beginningmind.dao.bm1.SecurityUsers2rolesMapper;
import com.spldeolin.beginningmind.model.SecurityUsers2roles;
import com.spldeolin.beginningmind.service.SecurityUsers2rolesService;
import lombok.extern.log4j.Log4j2;
import tk.mybatis.mapper.entity.Condition;

/**
 * “用户与权限的关联”业务实现
 *
 * @author Deolin 2018/5/28
 */
@Service
@Log4j2
public class SecurityUsers2rolesServiceImpl extends CommonServiceImpl<SecurityUsers2roles> implements
        SecurityUsers2rolesService {

    @Autowired
    private SecurityUsers2rolesMapper securityUsers2rolesMapper;

    @Override
    public Long createEX(SecurityUsers2roles securityUsers2roles) {
        /* 业务校验 */
        super.create(securityUsers2roles);
        return securityUsers2roles.getId();
    }

    @Override
    public void updateEX(SecurityUsers2roles securityUsers2roles) {
        if (!isExist(securityUsers2roles.getId())) {
            throw new ServiceException("用户与权限的关联不存在或是已被删除");
        }
        /* 业务校验 */
        if (!super.update(securityUsers2roles)) {
            throw new ServiceException("用户与权限的关联数据过时");
        }
    }

    @Override
    public void deleteEX(Long id) {
        if (!isExist(id)) {
            throw new ServiceException("用户与权限的关联不存在或是已被删除");
        }
        /* 业务校验 */
        super.delete(id);
    }

    @Override
    public String deleteEX(List<Long> ids) {
        List<SecurityUsers2roles> exist = super.get(ids);
        if (exist.size() == 0) {
            throw new ServiceException("选中的用户与权限的关联全部不存在或是已被删除");
        }
        /* 业务校验 */
        super.delete(ids);
        return "操作成功";
    }

    @Override
    public Page<SecurityUsers2roles> page(Integer pageNo, Integer pageSize) {
        Condition condition = new Condition(SecurityUsers2roles.class);
        condition.createCriteria()/* 添加条件 */;
        PageHelper.startPage(pageNo, pageSize);
        return Page.wrap(securityUsers2rolesMapper.selectBatchByCondition(condition));
    }

}