/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.dao.bm1;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.api.CommonMapper;
import com.spldeolin.beginningmind.model.SecurityAccounts2roles;

/**
 * “帐号与权限的关联”数据库映射
 *
 * @author Deolin 2018/5/15
 */
@Mapper
public interface SecurityAccounts2rolesMapper extends CommonMapper<SecurityAccounts2roles> {
}