/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.dao.bm1;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.api.CommonMapper;
import com.spldeolin.beginningmind.model.SecurityAccount;

/**
 * “帐号”数据库映射
 *
 * @author Deolin 2018/5/15
 */
@Mapper
public interface SecurityAccountMapper extends CommonMapper<SecurityAccount> {
}