/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.service.impl;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.time.LocalDateTime;
import java.util.Map.Entry;
import javax.servlet.http.HttpServletRequest;
import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.reflect.MethodSignature;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.LocalVariableTableParameterNameDiscoverer;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestBody;
import com.spldeolin.beginningmind.core.api.CommonServiceImpl;
import com.spldeolin.beginningmind.core.aspect.dto.RequestResult;
import com.spldeolin.beginningmind.core.model.RequestTrack;
import com.spldeolin.beginningmind.core.model.User;
import com.spldeolin.beginningmind.core.service.RequestTrackService;
import com.spldeolin.beginningmind.core.service.UserService;
import com.spldeolin.beginningmind.core.util.Jsons;
import com.spldeolin.beginningmind.core.util.StringRandomUtils;
import lombok.extern.log4j.Log4j2;

/**
 * “请求轨迹”业务实现
 *
 * @author Deolin 2018/8/4
 */
@Service
@Log4j2
public class RequestTrackServiceImpl extends CommonServiceImpl<RequestTrack> implements RequestTrackService {

    @Autowired
    private UserService userService;

    @Override
    public RequestTrack setJoinPointAndHttpRequest(JoinPoint joinPoint, HttpServletRequest request, Long userId) {
        RequestTrack track = new RequestTrack();

        track.setInsignia(StringRandomUtils.generateLegibleEnNum(6));

        track.setRequestedAt(LocalDateTime.now());

        track.setController(joinPoint.getTarget().getClass().getSimpleName());

        Method requestMethod = ((MethodSignature) joinPoint.getSignature()).getMethod();
        track.setRequestMethod(requestMethod.getName());

        track.setSignedUserId(userId);

        track.setMethod(requestMethod);

        Parameter[] parameters = requestMethod.getParameters();
        for (int i = 0; i < parameters.length; i++) {
            if (isRequestBody(parameters[i])) {
                track.setRequestBodyParameterIndex(i);
            }
        }

        String[] parameterNames = new LocalVariableTableParameterNameDiscoverer().getParameterNames(requestMethod);
        track.setParameterNames(parameterNames);

        Object[] parameterValues = joinPoint.getArgs();
        track.setParameterValues(parameterValues);

        return track;
    }

    @Async
    @Override
    public void completeAndSaveTrack(RequestTrack track, HttpServletRequest request, Object dataObject) {
        analysizRequestTrack(track, request);
        track.setResponseBody(Jsons.toJson(ensureRequestResult(dataObject)));
        super.create(track);
    }

    @Async
    @Override
    public void completeAndSaveTrack(RequestTrack track, HttpServletRequest request, RequestResult requestResult) {
        analysizRequestTrack(track, request);
        track.setResponseBody(Jsons.toJson(requestResult));
        super.create(track);
    }

    private void analysizRequestTrack(RequestTrack track, HttpServletRequest request) {
        track.setUrl(getFullUrlFromRequest(request));

        track.setHttpMethod(request.getMethod());

        track.setProcessingMilliseconds(System.currentTimeMillis() - track.getProcessedAt());

        Long signedUserId = track.getSignedUserId();
        if (signedUserId != null) {
            User user = userService.getEX(track.getSignedUserId());
            track.setSignedUserName(user.getName());
            track.setSignedUserMobile(user.getMobile());
        } else {
            track.setSignedUserName("");
            track.setSignedUserMobile("");
        }

        Object requestBodyParameterValue = null;
        Annotation[][] annotations = track.getMethod().getParameterAnnotations();
        outter:
        for (int parameterIndex = 0; parameterIndex < annotations.length; parameterIndex++) {
            Annotation[] annotationsEachParameter = annotations[parameterIndex];
            for (Annotation annotation : annotationsEachParameter) {
                if (annotation instanceof RequestBody) {
                    requestBodyParameterValue = track.getParameterValues()[parameterIndex];
                    break outter;
                }
            }
        }
        if (requestBodyParameterValue != null) {
            track.setRequestBody(Jsons.toJson(requestBodyParameterValue));
        } else {
            track.setRequestBody("");
        }
    }

    private RequestResult ensureRequestResult(Object object) {
        if (object instanceof RequestResult) {
            return (RequestResult) object;
        }
        return RequestResult.success(object);
    }

    private boolean isRequestBody(Parameter parameter) {
        return hasAnnotation(parameter, RequestBody.class);
    }

    private boolean hasAnnotation(Parameter parameter, Class<? extends Annotation> annotationType) {
        for (Annotation annotation : parameter.getAnnotations()) {
            if (annotation.getClass() == annotationType) {
                return true;
            }
        }
        return false;
    }

    private String getFullUrlFromRequest(HttpServletRequest request) {
        StringBuilder url = new StringBuilder(64);
        url.append(request.getRequestURL());
        for (Entry<String, String[]> queryValuesEachKey : request.getParameterMap().entrySet()) {
            String queryKey = queryValuesEachKey.getKey();
            for (String queryValue : queryValuesEachKey.getValue()) {
                if (queryValue != null) {
                    url.append("&");
                    url.append(queryKey);
                    url.append("=");
                    url.append(queryValue);
                }
            }
        }
        return url.toString().replaceFirst("&", "?");
    }

}