/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.service.impl;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.spldeolin.beginningmind.core.api.CommonServiceImpl;
import com.spldeolin.beginningmind.core.dao.RequestTrackMapper;
import com.spldeolin.beginningmind.core.model.RequestTrack;
import com.spldeolin.beginningmind.core.service.RequestTrackService;
import lombok.extern.log4j.Log4j2;
import tk.mybatis.mapper.entity.Condition;
import com.spldeolin.beginningmind.core.api.exception.ServiceException;
import com.spldeolin.beginningmind.core.api.dto.Page;
import com.spldeolin.beginningmind.core.api.dto.PageParam;
import com.github.pagehelper.PageHelper;
import tk.mybatis.mapper.entity.Condition;
import tk.mybatis.mapper.entity.Example;

/**
 * “请求轨迹”业务实现
 *
 * @author Deolin 2018/8/4
 */
@Service
@Log4j2
public class RequestTrackServiceImpl extends CommonServiceImpl<RequestTrack> implements RequestTrackService {

    @Autowired
    private RequestTrackMapper requestTrackMapper;

    @Override
    public Long createEX(RequestTrack requestTrack) {
        /* 业务校验 */
        super.create(requestTrack);
        return requestTrack.getId();
    }

    @Override
    public RequestTrack getEX(Long id) {
        return super.get(id).orElseThrow(() -> new ServiceException("请求轨迹不存在或是已被删除"));
    }

    @Override
    public void updateEX(RequestTrack requestTrack) {
        if (!isExist(requestTrack.getId())) {
            throw new ServiceException("请求轨迹不存在或是已被删除");
        }
        /* 业务校验 */
        if (!super.update(requestTrack)) {
            throw new ServiceException("请求轨迹数据过时");
        }
    }

    @Override
    public void deleteEX(Long id) {
        if (!isExist(id)) {
            throw new ServiceException("请求轨迹不存在或是已被删除");
        }
        /* 业务校验 */
        super.delete(id);
    }

    @Override
    public String deleteEX(List<Long> ids) {
        List<RequestTrack> exist = super.get(ids);
        if (exist.size() == 0) {
            throw new ServiceException("选中的请求轨迹全部不存在或是已被删除");
        }
        /* 业务校验 */
        super.delete(ids);
        return "操作成功";
    }

    @Override
    public Page<RequestTrack> page(PageParam pageParam) {
        Condition condition = new Condition(RequestTrack.class);
        condition.createCriteria()/* 添加条件 */;
        pageParam.startPage();
        return Page.wrap(requestTrackMapper.selectBatchByCondition(condition));
    }

}