/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.service.impl;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.github.pagehelper.PageHelper;
import com.spldeolin.beginningmind.core.api.CommonServiceImpl;
import com.spldeolin.beginningmind.core.api.dto.Page;
import com.spldeolin.beginningmind.core.api.exception.ServiceException;
import com.spldeolin.beginningmind.core.dao.SecurityUsers2permissionsMapper;
import com.spldeolin.beginningmind.core.model.SecurityUsers2permissions;
import com.spldeolin.beginningmind.core.service.SecurityUsers2permissionsService;
import lombok.extern.log4j.Log4j2;
import tk.mybatis.mapper.entity.Condition;

/**
 * “用户与权限的关联”业务实现
 *
 * @author Deolin 2018/6/3
 */
@Service
@Log4j2
public class SecurityUsers2permissionsServiceImpl extends CommonServiceImpl<SecurityUsers2permissions> implements
        SecurityUsers2permissionsService {

    @Autowired
    private SecurityUsers2permissionsMapper securityUsers2permissionsMapper;

    @Override
    public Long createEX(SecurityUsers2permissions securityUsers2permissions) {
        /* 业务校验 */
        super.create(securityUsers2permissions);
        return securityUsers2permissions.getId();
    }

    @Override
    public void updateEX(SecurityUsers2permissions securityUsers2permissions) {
        if (!isExist(securityUsers2permissions.getId())) {
            throw new ServiceException("用户与权限的关联不存在或是已被删除");
        }
        /* 业务校验 */
        if (!super.update(securityUsers2permissions)) {
            throw new ServiceException("用户与权限的关联数据过时");
        }
    }

    @Override
    public void deleteEX(Long id) {
        if (!isExist(id)) {
            throw new ServiceException("用户与权限的关联不存在或是已被删除");
        }
        /* 业务校验 */
        super.delete(id);
    }

    @Override
    public String deleteEX(List<Long> ids) {
        List<SecurityUsers2permissions> exist = super.get(ids);
        if (exist.size() == 0) {
            throw new ServiceException("选中的用户与权限的关联全部不存在或是已被删除");
        }
        /* 业务校验 */
        super.delete(ids);
        return "操作成功";
    }

    @Override
    public Page<SecurityUsers2permissions> page(Integer pageNo, Integer pageSize) {
        Condition condition = new Condition(SecurityUsers2permissions.class);
        condition.createCriteria()/* 添加条件 */;
        PageHelper.startPage(pageNo, pageSize);
        return Page.wrap(securityUsers2permissionsMapper.selectBatchByCondition(condition));
    }

}