/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.controller;

import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.spldeolin.beginningmind.core.api.exception.ServiceException;
import com.spldeolin.beginningmind.core.controller.annotation.DocClass;
import com.spldeolin.beginningmind.core.controller.annotation.DocMethod;
import com.spldeolin.beginningmind.core.controller.annotation.Permission;
import com.spldeolin.beginningmind.core.input.GoodsInput;
import com.spldeolin.beginningmind.core.model.Goods;
import com.spldeolin.beginningmind.core.service.GoodsService;

/**
 * “商品”管理
 *
 * @author Deolin 2018/5/26
 */
@DocClass(name = "商品管理", developer = "Deolin", date = "2018/05/26")
@RestController
@RequestMapping("/goods")
@Validated
public class GoodsController {

    @Autowired
    private GoodsService goodsService;

    /**
     * 创建一个“商品”
     */
    @DocMethod(desc = "创建一个商品", returnType = Long.class)
    @Permission(displayName = "创建商品")
    @PostMapping("/create")
    Object create(@RequestBody @Valid GoodsInput goodsInput) {
        return goodsService.createEX(goodsInput.toModel());
    }

    /**
     * 获取一个“商品”
     */
    @DocMethod(desc = "获取一个商品", returnType = Goods.class)
    @Permission(displayName = "商品详情")
    @GetMapping("/get/{id}")
    Object get(@PathVariable Long id) {
        return goodsService.get(id).orElseThrow(() -> new ServiceException("商品不存在或是已被删除"));
    }

    /**
     * 更新一个“商品”
     */
    @DocMethod(desc = "更新一个商品", returnType = Void.class)
    @Permission(displayName = "更新商品")
    @PostMapping("/update/{id}")
    Object update(@PathVariable Long id, @RequestBody @Valid GoodsInput goodsInput) {
        goodsService.updateEX(goodsInput.toModel().setId(id));
        return null;
    }

    /**
     * 删除一个“商品”
     */
    @DocMethod(desc = "删除一个商品", returnType = Void.class)
    @Permission(displayName = "删除商品")
    @PostMapping("/delete/{id}")
    Object delete(@PathVariable Long id) {
        goodsService.deleteEX(id);
        return null;
    }

    /**
     * 获取一批“商品”
     */
    @DocMethod(desc = "获取一批商品", returnType = Goods.class, isReturnList = true)
    @Permission(displayName = "商品列表")
    @GetMapping("/search")
    Object page(@RequestParam(defaultValue = "1") Integer pageNo,
            @RequestParam(defaultValue = "10") @Max(1000) Integer pageSize) {
        return goodsService.page(pageNo, pageSize);
    }

    /**
     * 删除一批“商品”
     */
    @DocMethod(desc = "删除一批商品", returnType = String.class)
    @Permission(displayName = "批量删除商品")
    @PostMapping("/batchDelete")
    Object delete(@RequestBody List<Long> ids) {
        return goodsService.deleteEX(ids);
    }

}