/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.controller;

import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.spldeolin.beginningmind.core.api.dto.Page;
import com.spldeolin.beginningmind.core.controller.annotation.Author;
import com.spldeolin.beginningmind.core.controller.annotation.Description;
import com.spldeolin.beginningmind.core.controller.annotation.Permission;
import com.spldeolin.beginningmind.core.controller.annotation.ReturnStruction;
import com.spldeolin.beginningmind.core.input.SecurityRoleInput;
import com.spldeolin.beginningmind.core.model.SecurityRole;
import com.spldeolin.beginningmind.core.service.SecurityRoleService;

/**
 * “角色”管理
 *
 * @author Deolin 2018/5/26
 */
@Description("角色管理的描述")
@Author(value = "没有名字的怪物", date = "2018/6/12")
@RestController
@RequestMapping(value = "/securityRole", produces = "application/json")
@Validated
public class SecurityRoleController {

    @Autowired
    private SecurityRoleService securityRoleService;

    /**
     * 创建一个“角色”
     */
    @Description("创建角色的描述")
    @ReturnStruction(type = SecurityRole.class, isPage = true)
    @Permission(displayName = "创建角色")
    @RequestMapping(value = "/create", method = RequestMethod.POST)
    Long create(@RequestBody @Valid SecurityRoleInput securityRoleInput) {
        return securityRoleService.createEX(securityRoleInput.toModel());
    }

    /**
     * 获取一个“角色”
     */
    @ReturnStruction(type = String.class, isArray = true)
    @Author("有趣")
    @Permission(displayName = "角色详情")
    @GetMapping("/get/{id}")
    SecurityRole get(@PathVariable Long id) {
        return securityRoleService.getEX(id);
    }

    /**
     * 更新一个“角色”
     */
    @Permission(displayName = "更新角色")
    @PostMapping("/update/{id}")
    void update(@PathVariable Long id, @RequestBody @Valid SecurityRoleInput securityRoleInput) {
        securityRoleService.updateEX(securityRoleInput.toModel().setId(id));
    }

    /**
     * 删除一个“角色”
     */
    @Permission(displayName = "删除角色")
    @PostMapping("/delete/{id}")
    void delete(@PathVariable Long id) {
        securityRoleService.deleteEX(id);
    }

    /**
     * 获取一批“角色”
     */
    @Permission(displayName = "角色列表")
    @GetMapping("/search")
    Page<SecurityRole> page(@RequestParam(defaultValue = "1") Integer pageNo,
            @RequestParam(defaultValue = "10") @Max(1000) Integer pageSize) {
        return securityRoleService.page(pageNo, pageSize);
    }

    /**
     * 删除一批“角色”
     */
    @Permission(displayName = "批量删除角色")
    @PostMapping("/batchDelete")
    String delete(@RequestBody List<Long> ids) {
        return securityRoleService.deleteEX(ids);
    }

}