/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.Goods;

/**
 * “商品”数据库映射
 *
 * @author Deolin 2018/5/15
 */
@Mapper
public interface GoodsMapper extends CommonMapper<Goods> {
}