/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.Organization;

/**
 * “组织架构”数据库映射
 *
 * @author Deolin 2018/8/28
 */
@Mapper
public interface OrganizationMapper extends CommonMapper<Organization> {

}