/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.RequestTrack;

/**
 * “请求轨迹”数据库映射
 *
 * @author Deolin 2018/8/4
 */
@Mapper
public interface RequestTrackMapper extends CommonMapper<RequestTrack> {

}