/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.SecurityUsers2menus;

/**
 * “用户与菜单的关联”数据库映射
 *
 * @author Deolin 2018/7/10
 */
@Mapper
public interface SecurityUsers2menusMapper extends CommonMapper<SecurityUsers2menus> {

}