/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.SecurityUsers2permissions;

/**
 * “用户与权限的关联”数据库映射
 *
 * @author Deolin 2018/6/3
 */
@Mapper
public interface SecurityUsers2permissionsMapper extends CommonMapper<SecurityUsers2permissions> {
}