/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.SecurityUsers2roles;

/**
 * “用户与权限的关联”数据库映射
 *
 * @author Deolin 2018/5/28
 */
@Mapper
public interface SecurityUsers2rolesMapper extends CommonMapper<SecurityUsers2roles> {
}