/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */

package com.spldeolin.beginningmind.core.dao;

import org.apache.ibatis.annotations.Mapper;
import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.Seller;

/**
 * “卖家”数据库映射
 *
 * @author Deolin 2018/5/15
 */
@Mapper
public interface SellerMapper extends CommonMapper<Seller> {
}