/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */
package com.spldeolin.beginningmind.core.dao;

import com.spldeolin.beginningmind.core.api.CommonMapper;
import com.spldeolin.beginningmind.core.model.User2organization;

import org.apache.ibatis.annotations.Mapper;
/**
 * “用户与组织架构的关联”数据库映射
 *
 * @author Deolin 2018/8/28
 */
@Mapper
public interface User2organizationMapper extends CommonMapper<User2organization> {
}